export enum movieGenres {
  ACTION = 'action',
  ADVENTURE = 'adventure',
  SCIFI = 'sci-fi',
  COMEDY = 'comedy',
  DRAMA = 'drama',
  FANTASY = 'fantasy',
  MUSICAL = 'musical',
  THRILLER = 'thriller',
  HORROR = 'horror',
  WESTERN = 'western',
  WAR = 'war',
  HISTORICAL = 'historical',
  CRIME = 'crime',
  NOIR = 'noir',
  ROMANCE = 'romance',
  ANIMATION = 'animation',
  DOCUMENTARY = 'documentary',
  SUPERHEROES = 'superheroes',
}
